### ISSUE TITLE
error after i update to 0.1.5.

### ISSUE THREAD

**Issue by superharaldsson** [erikarenhill/solaredge-modbus-hass#59]
Get this error message after i update to 0.1.5 via hacs
Home assistant Core 2024.1.2

Logger: homeassistant.setup
Source: setup.py:332
First occurred: 07:52:16 (1 occurrences)
Last logged: 07:52:16

Error during setup of component solaredge_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 332, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/solaredge_modbus/__init__.py", line 33, in async_setup
    host = conf[CONF_HOST]
           ~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by superharaldsson** [comment]
Now it works again! Uninstalled and installed.
